### ISSUE TITLE
bug: the result of `String()` of `FixedAmountPlan` and `RatioPlan` don't include `EpochAmount` or `EpochRatio`.

### ISSUE THREAD

**Issue by hallazzang** [tendermint/farming#207]
Currently `String()` method both `FixedAmountPlan` and `RatioPlan` use is implemented only in `BasePlan`.
We need to implement `String()` for both types to correctly include `EpochAmount` or `EpochRatio` in the result.

Also, we should discuss whether to use `MarshalYAML()` for `String()` or not.
We could just use the default `String()` implementation.
@dongsam @kogisin How do you think?

**Comment by dongsam** [comment]
@hallazzang
Is there a place where String() is currently used? Currently `farmingd q farming plans --output json | jq` or `http://127.0.0.1:1317/cosmos/farming/v1beta1/plans` returns with `@type` include EpochAmount or EpochRatio through `ctx.PrintProto` or `ctx.Codec.MarshalJSON`
```json
{
  "plans": [
    {
      "@type": "/cosmos.farming.v1beta1.RatioPlan",
      "base_plan": {
        "id": "1",
        "name": "First Public Ratio Plan",
        "type": "PLAN_TYPE_PUBLIC",
        "farming_pool_address": "cosmos1228ryjucdpdv3t87rxle0ew76a56ulvnfst0hq0sscd3nafgjpqqkcxcky",
        "termination_address": "cosmos1228ryjucdpdv3t87rxle0ew76a56ulvnfst0hq0sscd3nafgjpqqkcxcky",
        "staking_coin_weights": [
          {
            "denom": "pool93E069B333B5ECEBFE24C6E1437E814003248E0DD7FF8B9F82119F4587449BA5",
            "amount": "0.500000000000000000"
          },
          {
            "denom": "poolD35A0CC16EE598F90B044CE296A405BA9C381E38837599D96F2F70C2F02A23A4",
            "amount": "0.500000000000000000"
          }
        ],
        "start_time": "2021-09-01T00:00:00Z",
        "end_time": "2031-09-30T00:00:00Z",
        "terminated": false,
        "last_distribution_time": null,
        "distributed_coins": []
      },
      "epoch_ratio": "0.900000000000000000"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "0"
  }
}
```

**Comment by hallazzang** [comment]
I'm not 100% sure but I think we're using `yaml` representation for command line output when we don't specify `--output json`. I'll find out where it's used.

**Comment by dongsam** [comment]
@hallazzang  Yes, Thanks, here is the result when we call `farmingd q farming plans`  or `farmingd q farming plans --output text`
```yaml
pagination:
  next_key: null
  total: "0"
plans:
- '@type': /cosmos.farming.v1beta1.RatioPlan
  base_plan:
    distributed_coins: []
    end_time: "2031-09-30T00:00:00Z"
    farming_pool_address: cosmos1228ryjucdpdv3t87rxle0ew76a56ulvnfst0hq0sscd3nafgjpqqkcxcky
    id: "1"
    last_distribution_time: null
    name: First Public Ratio Plan
    staking_coin_weights:
    - amount: "0.500000000000000000"
      denom: pool93E069B333B5ECEBFE24C6E1437E814003248E0DD7FF8B9F82119F4587449BA5
    - amount: "0.500000000000000000"
      denom: poolD35A0CC16EE598F90B044CE296A405BA9C381E38837599D96F2F70C2F02A23A4
    start_time: "2021-09-01T00:00:00Z"
    terminated: false
    termination_address: cosmos1228ryjucdpdv3t87rxle0ew76a56ulvnfst0hq0sscd3nafgjpqqkcxcky
    type: PLAN_TYPE_PUBLIC
  epoch_ratio: "0.900000000000000000"
  ```
